[project]
name = "jira-brain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kyle Vassella", email = "kylevassella@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "anthropic>=1.8.0",
    "chromadb>=1.5.9",
    "fastapi>=0.141.1",
    "langsmith>=0.14.3",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.54.0",
]

[project.scripts]
jira-brain = "jira_brain:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
